{% set name = "eliot-tree" %}
{% set version = "21.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 85397eafe4093cf43bb2cef796dcb75a6ec32f2d922869a6808b89c77f2294ef

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - eliot-tree = eliottree._cli:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - six
    - jmespath
    - iso8601
    - colored
    - toolz
    - eliot
    - win-unicode-console  # [win]
test:
  commands:
    - eliot-tree --help

about:
  home: https://github.com/jonathanj/eliottree
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Render Eliot logs as an ASCII tree

  description: Render Eliot logs as an ASCII tree
  doc_url: https://github.com/jonathanj/eliottree
  dev_url: https://github.com/jonathanj/eliottree

extra:
  recipe-maintainers:
    - itamarst
