{% set name = "eliot-tree" %}
{% set version = "19.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: aac20b528944e6e3c9d33884104f06a8de3a1840ada15d07ea036e50b58cfba1

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - eliot-tree = eliottree._cli:main

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - six
    - jmespath
    - iso8601
    - colored
    - toolz
    - eliot
    - win-unicode-console #[win]
test:
  commands:
    - eliot-tree --help

about:
  home: https://github.com/jonathanj/eliottree
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Render Eliot logs as an ASCII tree'

  description: 'Render Eliot logs as an ASCII tree'
  doc_url: https://github.com/jonathanj/eliottree
  dev_url: https://github.com/jonathanj/eliottree

extra:
  recipe-maintainers:
    - itamarst
