travis:
  secure:
    BINSTAR_TOKEN: R960/CVjHfpgpAIgxtMpowcdwY1F7MVfEPyVv+2lr1r6tVccpuFF+tYEc09gl5CDc5yxVzLkyjwvmE5iMClbLBYHvYHupG2NTqOsGBJZPGu17TEJbgwFz+GEbaA+bNLkMNtb79vOqKoZW91+0zTJB+/NTTP+/tEm3cbzBvXXvwb0UnMS1KaL60Onf6EA9c+ft/XEGC2vRGJtUZVCAaXL+jKnH94KrWhEddygNQqkNRwx+E2NnNXnVoyofqGVKl+WzhMy0OSdHujUM/qreOmsIwN2aJ8n82RbYIh0bx08QZ6l08hdnz3HKBpn5kPEd5EEgMt5WUhG944D7M5xsug1dlzuAUm6iq5d/PBJHeY0bui3sZzRpZbUZbeXXSg7QLlMbBWrtgQNBYQenfJIzKO4/0QyN0L1Qp0qLnWcPzu+9Z1RlFTImlfSmZRlOUnU1qMfClyWTDj6wqHihppG5VLr33Dew2QcocWj9Gs9DzHtqg4qMGmGHVe9V6lnYfauzhhLDxW/oYXzNNVUa2gTf4bM+hW7m8hKULkYmiK1FvipxzdW7G5rclr2DzGHq0ppaBvQLBBVRwIZVdwMz749WWR3HmmPZd81LaruamFk2gsK2OSZlectKVweDfidklIxiQyt57370lBFQd89wTnO6xWBrpvTOdLkNZMGMMTaELMjmp4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
